name: Build and Upload ISO

on:
  push:
    branches:
      - trunk  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # using Ubuntu as an example, adjust as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make xorriso qemu-system-x86_64
          # For macOS only
          # brew install x86_64-elf-gcc x86_64-elf-ld

      - name: Build ISO
        run: make all

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v2
        with:
          name: template.iso
          path: template.iso
