name: Build and Upload ISO

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make xorriso qemu

      - name: Build ISO
        run: make all

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v2
        with:
          name: template.iso
          path: template.iso
